version: '3'
services:
  web:
    build: .
    #links: 
    #  - db
    ports:
      - 8080:8080
    network_mode: bridge
  db:
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: FileStorage
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    network_mode: bridge